// Mocks generated by Mockito 5.4.4 from annotations
// in idec_conference_app/test/enhanced_auth_system_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:idec_conference_app/models/auth_models.dart' as _i2;
import 'package:idec_conference_app/models/user_model.dart' as _i6;
import 'package:idec_conference_app/services/connectivity_service.dart' as _i5;
import 'package:idec_conference_app/services/offline_storage_service.dart'
    as _i8;
import 'package:idec_conference_app/services/secure_token_manager.dart' as _i7;
import 'package:idec_conference_app/services/session_manager.dart' as _i9;
import 'package:idec_conference_app/services/unified_auth_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthState_0 extends _i1.SmartFake implements _i2.AuthState {
  _FakeAuthState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthResult_1 extends _i1.SmartFake implements _i2.AuthResult {
  _FakeAuthResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UnifiedAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUnifiedAuthService extends _i1.Mock
    implements _i3.UnifiedAuthService {
  MockUnifiedAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.AuthState> get authStateStream => (super.noSuchMethod(
        Invocation.getter(#authStateStream),
        returnValue: _i4.Stream<_i2.AuthState>.empty(),
      ) as _i4.Stream<_i2.AuthState>);

  @override
  _i4.Stream<_i5.ConnectivityStatus> get connectivityStream =>
      (super.noSuchMethod(
        Invocation.getter(#connectivityStream),
        returnValue: _i4.Stream<_i5.ConnectivityStatus>.empty(),
      ) as _i4.Stream<_i5.ConnectivityStatus>);

  @override
  _i2.AuthState get currentAuthState => (super.noSuchMethod(
        Invocation.getter(#currentAuthState),
        returnValue: _FakeAuthState_0(
          this,
          Invocation.getter(#currentAuthState),
        ),
      ) as _i2.AuthState);

  @override
  _i4.Future<_i2.AuthResult> login({
    required String? phone,
    required String? password,
    bool? rememberMe = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #phone: phone,
            #password: password,
            #rememberMe: rememberMe,
          },
        ),
        returnValue: _i4.Future<_i2.AuthResult>.value(_FakeAuthResult_1(
          this,
          Invocation.method(
            #login,
            [],
            {
              #phone: phone,
              #password: password,
              #rememberMe: rememberMe,
            },
          ),
        )),
      ) as _i4.Future<_i2.AuthResult>);

  @override
  _i4.Future<_i2.AuthResult> register({
    required String? phone,
    required String? password,
    required String? firstName,
    required String? lastName,
    String? email,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #phone: phone,
            #password: password,
            #firstName: firstName,
            #lastName: lastName,
            #email: email,
          },
        ),
        returnValue: _i4.Future<_i2.AuthResult>.value(_FakeAuthResult_1(
          this,
          Invocation.method(
            #register,
            [],
            {
              #phone: phone,
              #password: password,
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
            },
          ),
        )),
      ) as _i4.Future<_i2.AuthResult>);

  @override
  _i4.Future<_i2.AuthResult> requestOtp({
    required String? phone,
    String? purpose = r'verification',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestOtp,
          [],
          {
            #phone: phone,
            #purpose: purpose,
          },
        ),
        returnValue: _i4.Future<_i2.AuthResult>.value(_FakeAuthResult_1(
          this,
          Invocation.method(
            #requestOtp,
            [],
            {
              #phone: phone,
              #purpose: purpose,
            },
          ),
        )),
      ) as _i4.Future<_i2.AuthResult>);

  @override
  _i4.Future<_i2.AuthResult> verifyOtp({
    required String? phone,
    required String? otp,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOtp,
          [],
          {
            #phone: phone,
            #otp: otp,
          },
        ),
        returnValue: _i4.Future<_i2.AuthResult>.value(_FakeAuthResult_1(
          this,
          Invocation.method(
            #verifyOtp,
            [],
            {
              #phone: phone,
              #otp: otp,
            },
          ),
        )),
      ) as _i4.Future<_i2.AuthResult>);

  @override
  _i4.Future<_i2.AuthResult> logout({bool? fromAllDevices = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
          {#fromAllDevices: fromAllDevices},
        ),
        returnValue: _i4.Future<_i2.AuthResult>.value(_FakeAuthResult_1(
          this,
          Invocation.method(
            #logout,
            [],
            {#fromAllDevices: fromAllDevices},
          ),
        )),
      ) as _i4.Future<_i2.AuthResult>);

  @override
  _i4.Future<bool> refreshToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> isSessionValid() => (super.noSuchMethod(
        Invocation.method(
          #isSessionValid,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i6.UserModel?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i4.Future<_i6.UserModel?>.value(),
      ) as _i4.Future<_i6.UserModel?>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [SecureTokenManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureTokenManager extends _i1.Mock
    implements _i7.SecureTokenManager {
  MockSecureTokenManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveTokens({
    required String? accessToken,
    required String? refreshToken,
    required int? expiresIn,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTokens,
          [],
          {
            #accessToken: accessToken,
            #refreshToken: refreshToken,
            #expiresIn: expiresIn,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getValidAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getValidAccessToken,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<String?> getRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #getRefreshToken,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<bool> isAccessTokenValid() => (super.noSuchMethod(
        Invocation.method(
          #isAccessTokenValid,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> hasValidTokens() => (super.noSuchMethod(
        Invocation.method(
          #hasValidTokens,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<Duration?> getTimeUntilExpiry() => (super.noSuchMethod(
        Invocation.method(
          #getTimeUntilExpiry,
          [],
        ),
        returnValue: _i4.Future<Duration?>.value(),
      ) as _i4.Future<Duration?>);

  @override
  _i4.Future<void> clearTokens() => (super.noSuchMethod(
        Invocation.method(
          #clearTokens,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> verifyTokenIntegrity() => (super.noSuchMethod(
        Invocation.method(
          #verifyTokenIntegrity,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, dynamic>> getTokenInfo() => (super.noSuchMethod(
        Invocation.method(
          #getTokenInfo,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [OfflineStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOfflineStorageService extends _i1.Mock
    implements _i8.OfflineStorageService {
  MockOfflineStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cacheUserData(Map<String, dynamic>? userData) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheUserData,
          [userData],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> getCachedUserData() => (super.noSuchMethod(
        Invocation.method(
          #getCachedUserData,
          [],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> cacheAuthData(Map<String, dynamic>? authData) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheAuthData,
          [authData],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> getCachedAuthData() => (super.noSuchMethod(
        Invocation.method(
          #getCachedAuthData,
          [],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> addPendingOperation({
    required String? operation,
    required Map<String, dynamic>? data,
    String? endpoint,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPendingOperation,
          [],
          {
            #operation: operation,
            #data: data,
            #endpoint: endpoint,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> syncPendingOperations() => (super.noSuchMethod(
        Invocation.method(
          #syncPendingOperations,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAuthData() => (super.noSuchMethod(
        Invocation.method(
          #clearAuthData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<DateTime?> getLastSyncTime() => (super.noSuchMethod(
        Invocation.method(
          #getLastSyncTime,
          [],
        ),
        returnValue: _i4.Future<DateTime?>.value(),
      ) as _i4.Future<DateTime?>);

  @override
  _i4.Future<int> getPendingOperationsCount() => (super.noSuchMethod(
        Invocation.method(
          #getPendingOperationsCount,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<Map<String, dynamic>> getStorageInfo() => (super.noSuchMethod(
        Invocation.method(
          #getStorageInfo,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [SessionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionManager extends _i1.Mock implements _i9.SessionManager {
  MockSessionManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i9.SessionEvent> get sessionEvents => (super.noSuchMethod(
        Invocation.getter(#sessionEvents),
        returnValue: _i4.Stream<_i9.SessionEvent>.empty(),
      ) as _i4.Stream<_i9.SessionEvent>);

  @override
  _i4.Stream<_i9.SessionStatus> get statusStream => (super.noSuchMethod(
        Invocation.getter(#statusStream),
        returnValue: _i4.Stream<_i9.SessionStatus>.empty(),
      ) as _i4.Stream<_i9.SessionStatus>);

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> startSession(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #startSession,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> endSession() => (super.noSuchMethod(
        Invocation.method(
          #endSession,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateActivity() => (super.noSuchMethod(
        Invocation.method(
          #updateActivity,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isSessionActive() => (super.noSuchMethod(
        Invocation.method(
          #isSessionActive,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, dynamic>> getSessionInfo() => (super.noSuchMethod(
        Invocation.method(
          #getSessionInfo,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i5.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.ConnectivityStatus> get connectivityStream =>
      (super.noSuchMethod(
        Invocation.getter(#connectivityStream),
        returnValue: _i4.Stream<_i5.ConnectivityStatus>.empty(),
      ) as _i4.Stream<_i5.ConnectivityStatus>);

  @override
  _i4.Stream<bool> get isConnectedStream => (super.noSuchMethod(
        Invocation.getter(#isConnectedStream),
        returnValue: _i4.Stream<bool>.empty(),
      ) as _i4.Stream<bool>);

  @override
  _i5.ConnectivityStatus get currentStatus => (super.noSuchMethod(
        Invocation.getter(#currentStatus),
        returnValue: _i5.ConnectivityStatus.wifi,
      ) as _i5.ConnectivityStatus);

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> checkConnection() => (super.noSuchMethod(
        Invocation.method(
          #checkConnection,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i5.ConnectivityStatus> getCurrentConnectivityType() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentConnectivityType,
          [],
        ),
        returnValue: _i4.Future<_i5.ConnectivityStatus>.value(
            _i5.ConnectivityStatus.wifi),
      ) as _i4.Future<_i5.ConnectivityStatus>);

  @override
  _i4.Future<void> waitForConnection({Duration? timeout}) =>
      (super.noSuchMethod(
        Invocation.method(
          #waitForConnection,
          [],
          {#timeout: timeout},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> getConnectivityInfo() => (super.noSuchMethod(
        Invocation.method(
          #getConnectivityInfo,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
