// Mocks generated by Mockito 5.4.4 from annotations
// in idec_conference_app/test/token_refresh_interceptor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:idec_conference_app/services/enhanced_session_manager.dart'
    as _i5;
import 'package:idec_conference_app/services/platform_storage_service.dart'
    as _i6;
import 'package:idec_conference_app/services/silent_token_refresh_service.dart'
    as _i2;
import 'package:idec_conference_app/services/unified_token_manager.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRefreshStatistics_0 extends _i1.SmartFake
    implements _i2.RefreshStatistics {
  _FakeRefreshStatistics_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UnifiedTokenManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockUnifiedTokenManager extends _i1.Mock
    implements _i3.UnifiedTokenManager {
  MockUnifiedTokenManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i3.SessionEvent> get sessionEvents => (super.noSuchMethod(
        Invocation.getter(#sessionEvents),
        returnValue: _i4.Stream<_i3.SessionEvent>.empty(),
      ) as _i4.Stream<_i3.SessionEvent>);

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveTokens({
    required String? accessToken,
    required String? refreshToken,
    required int? expiresIn,
    int? refreshExpiresIn,
    String? sessionId,
    Map<String, dynamic>? userData,
    Map<String, dynamic>? deviceInfo,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTokens,
          [],
          {
            #accessToken: accessToken,
            #refreshToken: refreshToken,
            #expiresIn: expiresIn,
            #refreshExpiresIn: refreshExpiresIn,
            #sessionId: sessionId,
            #userData: userData,
            #deviceInfo: deviceInfo,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getValidAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getValidAccessToken,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<bool> isAccessTokenValid() => (super.noSuchMethod(
        Invocation.method(
          #isAccessTokenValid,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> hasValidRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #hasValidRefreshToken,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> refreshAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshAccessToken,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> clearTokens() => (super.noSuchMethod(
        Invocation.method(
          #clearTokens,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #getRefreshToken,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<String?> getSessionId() => (super.noSuchMethod(
        Invocation.method(
          #getSessionId,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<Map<String, dynamic>?> getUserData() => (super.noSuchMethod(
        Invocation.method(
          #getUserData,
          [],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<bool> hasValidSession() => (super.noSuchMethod(
        Invocation.method(
          #hasValidSession,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, dynamic>> getTokenInfo() => (super.noSuchMethod(
        Invocation.method(
          #getTokenInfo,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<bool> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [EnhancedSessionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockEnhancedSessionManager extends _i1.Mock
    implements _i5.EnhancedSessionManager {
  MockEnhancedSessionManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.SessionStateEvent> get sessionStateStream =>
      (super.noSuchMethod(
        Invocation.getter(#sessionStateStream),
        returnValue: _i4.Stream<_i5.SessionStateEvent>.empty(),
      ) as _i4.Stream<_i5.SessionStateEvent>);

  @override
  _i4.Stream<_i5.SessionExpiredEvent> get sessionExpiredStream =>
      (super.noSuchMethod(
        Invocation.getter(#sessionExpiredStream),
        returnValue: _i4.Stream<_i5.SessionExpiredEvent>.empty(),
      ) as _i4.Stream<_i5.SessionExpiredEvent>);

  @override
  _i4.Stream<_i5.OfflineSessionEvent> get offlineSessionStream =>
      (super.noSuchMethod(
        Invocation.getter(#offlineSessionStream),
        returnValue: _i4.Stream<_i5.OfflineSessionEvent>.empty(),
      ) as _i4.Stream<_i5.OfflineSessionEvent>);

  @override
  _i5.SessionState get currentState => (super.noSuchMethod(
        Invocation.getter(#currentState),
        returnValue: _i5.SessionState.none,
      ) as _i5.SessionState);

  @override
  bool get isOnline => (super.noSuchMethod(
        Invocation.getter(#isOnline),
        returnValue: false,
      ) as bool);

  @override
  bool get isSessionActive => (super.noSuchMethod(
        Invocation.getter(#isSessionActive),
        returnValue: false,
      ) as bool);

  @override
  _i5.SessionState get sessionState => (super.noSuchMethod(
        Invocation.getter(#sessionState),
        returnValue: _i5.SessionState.none,
      ) as _i5.SessionState);

  @override
  _i4.Future<void> initialize({
    _i6.PlatformStorageService? storage,
    _i3.UnifiedTokenManager? tokenManager,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {
            #storage: storage,
            #tokenManager: tokenManager,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> startSession({
    required String? userId,
    required String? deviceId,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startSession,
          [],
          {
            #userId: userId,
            #deviceId: deviceId,
            #metadata: metadata,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateActivity({Map<String, dynamic>? metadata}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateActivity,
          [],
          {#metadata: metadata},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> endSession({String? reason}) => (super.noSuchMethod(
        Invocation.method(
          #endSession,
          [],
          {#reason: reason},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isSessionValid() => (super.noSuchMethod(
        Invocation.method(
          #isSessionValid,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i5.SessionData?> getCurrentSession() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentSession,
          [],
        ),
        returnValue: _i4.Future<_i5.SessionData?>.value(),
      ) as _i4.Future<_i5.SessionData?>);

  @override
  _i4.Future<int> getOfflineActivitiesCount() => (super.noSuchMethod(
        Invocation.method(
          #getOfflineActivitiesCount,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> syncOfflineActivities() => (super.noSuchMethod(
        Invocation.method(
          #syncOfflineActivities,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void notifySessionExpired({
    required String? reason,
    bool? shouldRedirectToLogin = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #notifySessionExpired,
          [],
          {
            #reason: reason,
            #shouldRedirectToLogin: shouldRedirectToLogin,
          },
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SilentTokenRefreshService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSilentTokenRefreshService extends _i1.Mock
    implements _i2.SilentTokenRefreshService {
  MockSilentTokenRefreshService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.RefreshAttemptResult> get attemptStream => (super.noSuchMethod(
        Invocation.getter(#attemptStream),
        returnValue: _i4.Stream<_i2.RefreshAttemptResult>.empty(),
      ) as _i4.Stream<_i2.RefreshAttemptResult>);

  @override
  _i4.Stream<_i2.RefreshStatistics> get statisticsStream => (super.noSuchMethod(
        Invocation.getter(#statisticsStream),
        returnValue: _i4.Stream<_i2.RefreshStatistics>.empty(),
      ) as _i4.Stream<_i2.RefreshStatistics>);

  @override
  _i2.RefreshStatistics get statistics => (super.noSuchMethod(
        Invocation.getter(#statistics),
        returnValue: _FakeRefreshStatistics_0(
          this,
          Invocation.getter(#statistics),
        ),
      ) as _i2.RefreshStatistics);

  @override
  bool get isRefreshing => (super.noSuchMethod(
        Invocation.getter(#isRefreshing),
        returnValue: false,
      ) as bool);

  @override
  bool get isOnline => (super.noSuchMethod(
        Invocation.getter(#isOnline),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> initialize({_i2.SilentRefreshConfig? config}) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {#config: config},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> triggerRefresh({String? reason = r'Manual trigger'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #triggerRefresh,
          [],
          {#reason: reason},
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  void updateConfig(_i2.SilentRefreshConfig? newConfig) => super.noSuchMethod(
        Invocation.method(
          #updateConfig,
          [newConfig],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pause() => super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resume() => super.noSuchMethod(
        Invocation.method(
          #resume,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
